"""criar tabela usuarios

Revision ID: ec12613fbb7f
Revises: 0001_baseline
Create Date: 2026-09-18 17:53:00.869184
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ec12613fbb7f'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('ADMIN', 'PROFESSOR', 'ALUNO', name='perfil_usuario'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email', name='uq_usuarios_email'),
    sa.UniqueConstraint('matricula', name='uq_usuarios_matricula')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
